CREATE TABLE IF NOT EXISTS BOOK (
	ID BIGSERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	AUTHOR VARCHAR(100) NOT NULL,
	YEAR VARCHAR(4) UNIQUE NOT NULL,
	PUBLISHER VARCHAR(50) NOT NULL,
	PRICE FLOAT NOT NULL,
	ISBN VARCHAR(13) NOT NULL
);